### PR TITLE
PositionValue lib: restrict to lower than solc version 8

### PR DESCRIPTION
**Pull request by ewilz**
fixes https://github.com/Uniswap/uniswap-v3-periphery/issues/198

### CODE REVIEW

**Comment by moodysalem** [comment]
what do we need in 0.7.0? would earlier versions work?

**Comment by ewilz** [comment]
> what do we need in 0.7.0? would earlier versions work?

hmm...well I see now our standard is to do from `>=0.5.0` however, I use the `TickMath` library which uses `type(uint256).max` which is new in `Solidity 0.6.8` even though TickMath also claims to compile from `>=0.5.0` But I don't think it will compile lower than 0.6.8

**Review by moodysalem — APPROVED** [review]

**Comment by Bulinlllll** [comment]
Tengo [https://github.com/github/docs/commit/9cc87413cb81b8bf94989c8130a4d04c33df1c12?short_path=eca12c0#commitcomment-55251941](position_value_solc)

**Comment by ewilz** [comment]
Changed to 0.6.8

**Pull request merged**
